# Stage 1
FROM mariadb:12.1.1-ubi10-rc

USER root
RUN groupadd www
RUN usermod -aG www mysql

WORKDIR /build

# Copy all of the database stuff
COPY ./*.sql /docker-entrypoint-initdb.d
COPY ./*.sh /docker-entrypoint-initdb.d
COPY ./server.cnf /etc/my.cnf.d

WORKDIR /data

EXPOSE 33060

# CMD ["/usr/sbin/mariadbd"]